<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
        <OutputType>WinExe</OutputType>
        <RootNamespace>ExploreDB</RootNamespace>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnableDefaultCssItems>false</EnableDefaultCssItems>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
        <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
        <WindowsPackageType>MSIX</WindowsPackageType>
        <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <Platforms>AnyCPU;x64</Platforms>
        <GenerateAppxPackageOnBuild>true</GenerateAppxPackageOnBuild>
        <GenerateTestAppPackage>true</GenerateTestAppPackage>
        <AppxPackageSigningEnabled>true</AppxPackageSigningEnabled>
        <ApplicationVersion>7</ApplicationVersion>
        <ApplicationDisplayVersion>1.1.3.0</ApplicationDisplayVersion>
        <Version>1.1.3.0</Version>
        <PublishReadyToRun>false</PublishReadyToRun>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
        <ApplicationIcon>Platforms\Windows\Images\app.ico</ApplicationIcon>
		
    </PropertyGroup>

    <PropertyGroup Condition="'$(StoreBuild)' == 'true'">
        <DefineConstants>$(DefineConstants);STORE_BUILD</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(GitHubRelease)' == 'true'">
        <PackageCertificateThumbprint>B0E20E1D115E17F7D5FAE21DD184ED1BE15BC081</PackageCertificateThumbprint>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BlazorMonaco" Version="3.5.0" />
        <PackageReference Include="Microsoft.Maui.Controls" Version="8.0.7" />
        <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.7" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="8.0.7" />
        <PackageReference Include="Microsoft.Graphics.Win2D" Version="1.0.5.1" />
        <PackageReference Include="Dapper" Version="2.1.28" />
        <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
      <MauiAsset Include="wwwroot\**" />
    </ItemGroup>

    <ItemGroup>
        <None Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="Platforms\Windows\Images\**">
            <Link>Images\%(RecursiveDir)%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>



</Project>
